import { NlpModel } from '@app/workbench/interfaces';
import { Color, ScaleType } from '@swimlane/ngx-charts';

export const SALES_EMAIL = 'sales@datastand.net';

export const SUPPORT_EMAIL = 'support@datastand.net';

export const OFF_MODEL_ID = '!off';

export const OFF_MODEL: NlpModel = {
  id: OFF_MODEL_ID,
  language: 'en',
  name: 'Off',
};

// Generated by:
// $ curl -X 'GET' \
//   'http://localhost:5757/annotate/models' \
//   -H 'accept: application/json'
export const ANNOTATE_MODELS: NlpModel[] = [
  {
    id: 'openai',
    language: 'en',
    name: 'Open AI (gpt-3.5-turbo)',
  },
];

// Generated by:
// $ curl -X 'GET' \
//    'http://localhost:5757/annotate-similar-spans/models' \
//    -H 'accept: application/json'
export const ANNOTATE_SIMILAR_SPANS_MODELS: NlpModel[] = [
  OFF_MODEL,
  {
    id: 'exact-match',
    language: 'en',
    name: 'Exact match',
  },
];

export const WHITESPACE_MODEL_ID = 'whitespace';
export const BYTES_MODEL_ID = 'bytes';
export const SENTENCES_MODEL_ID = 'sentences';

// Generated by:
// $ curl -X 'GET' \
//    'http://localhost:5757/tokenize/models' \
//    -H 'accept: application/json'
export const TOKENIZE_MODELS: NlpModel[] = [
  {
    id: BYTES_MODEL_ID,
    language: 'en',
    name: 'Bytes',
  },
  {
    id: SENTENCES_MODEL_ID,
    language: 'en',
    name: 'Sentences',
  },
  {
    id: WHITESPACE_MODEL_ID,
    language: 'en',
    name: 'Whitespace',
  },
];

export const TOKENIZE_MODELS_IDS = TOKENIZE_MODELS.map((model) => model.id);

export const NGX_COLOR_SCHEME: Color = {
  name: 'dataStand',
  selectable: true,
  group: ScaleType.Ordinal,
  domain: ['#f0cded'],
};

export const USERNAME_PATTERN = /^[a-z0-9_]+$/;
